import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/global.css";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.ico",
  },
};

const html = `
  h-full w-full
  bg-neutral-900 text-neutral-200`;

const body = `
  h-full w-full
  flex flex-col`;

const main = `
  px-20 py-4 h-full w-full`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={html}>
      <body className={`${inter.className} antialiased ${body}`}>
        <Header />
        <main className={main}>{children}</main>
      </body>
    </html>
  );
}
