import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/global.css";
import { Header } from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${inter.className} antialiased flex flex-col h-full w-full`}
      >
        <Header />
        <main className="p-4 h-full w-full">{children}</main>
      </body>
    </html>
  );
}
