import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/global.css";
import { Header } from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased flex flex-col`}>
        <Header />
        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
